version: "3.8"
services:
  app:
    build: .
    container_name: binance-php-app
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: development
    ports:
      - "8080:8080"

  front:
    build: ./binance-front
    container_name: binance-php-front
    depends_on:
      - app
    ports:
      - "5173:80"
